keymap:
  # # Map Super + C to actual Copy action
  # - name: "Super + C -> Copy"
  #   remap:
  #     Super_L-C: C-C
  #
  # # Map Super + V to actual Paste action
  # - name: "Super + V -> Paste"
  #   remap:
  #     Super_L-V: C-V
  #
  # # Map Super + A to Ctrl + A (Select All)
  # - name: "Super + A -> Ctrl + A"
  #   remap:
  #     Super_L-A: C-A
  #
  # # Map Super + F to Ctrl + F (Find)
  # - name: "Super + F -> Ctrl + F"
  #   remap:
  #     Super_L-F: C-F
  #
  # # Map Super + W to Ctrl + W (Close Tab/Window)
  # - name: "Super + W -> Ctrl + W"
  #   remap:
  #     Super_L-W: C-W
  #
  # # Map Super + Q to Ctrl + Q (Close App)
  # - name: "Super + Q -> Ctrl + Q"
  #   remap:
  #     Super_L-Q: C-Q
  #
  # # Map Super + N to Ctrl + N (Window)
  # - name: "Super + N -> Ctrl + N"
  #   remap:
  #     Super_L-N: C-N
  #
  # # Map Super + N to Ctrl + N (New Tab)
  # - name: "Super + T -> Ctrl + T"
  #   remap:
  #     Super_L-T: C-T

  - name: "Cmd + 1-9 to Ctrl + 1-9"
    remap:
      Super_L-1: C-1
      Super_L-2: C-2
      Super_L-3: C-3
      Super_L-4: C-4
      Super_L-5: C-5
      Super_L-6: C-6
      Super_L-7: C-7
      Super_L-8: C-8
      Super_L-9: C-9  

# Map Super + Tab to Alt + Tab (App Switching)
  # - name: "Super + Tab -> Alt + Tab"
  #   remap:
  #     Super_L-Tab: Alt-Tab

  # - name: "Super + l"
  #   remap:
  #     Super_L-L: C-L

  # - name: "Remap Cmd + ` and Cmd + Escape to Alt + `"
    # remap:
      # Remap Cmd + ` to Alt + `
      # SUPER-Grave: Alt-Grave
      # Remap Cmd + Escape to Alt + `
      # SUPER-Esc: Alt-Grave

  # Super + Alt + Slash (/) -> Launch Kitty terminal
  # - name: "Super + Alt + Slash -> Launch Kitty"
  #   remap:
  #     Super_L-Alt-Slash:
  #       launch: ["kitty"]

  # WINDOW MANAGEMENT
  - name: "Remap Cmd + Alt + H/J/K/L to Win + Arrow Keys"
    remap:
      # Cmd (Super) + Alt + H -> Win (Super) + Left
      SUPER-M-H: SUPER-Left
      # Cmd (Super) + Alt + J -> Win (Super) + Down
      SUPER-M-J: SUPER-Down
      # Cmd (Super) + Alt + K -> Win (Super) + Up
      SUPER-M-K: SUPER-Up
      # Cmd (Super) + Alt + L -> Win (Super) + Right
      SUPER-M-L: SUPER-Right

  # - name: "Remap CAPS + H/J/K/L to Arrow Keys"
  #   remap:
  #     CAPSLOCK-H: Left
  #     CAPSLOCK-J: Down
  #     CAPSLOCK-K: Up
  #     CAPSLOCK-L: Right

  - name: "Shift + Escape -> ~"
    remap:
      Shift-Esc: Shift-KEY_GRAVE

  # - name: "Remap Cmd + Tab to Alt + Tab"
  #   remap:
  #     SUPER-Tab: Alt-Tab

  # Super + Alt + Backspace -> Launch Browser
  # - name: "Super + Alt + Backspace -> Launch Browser"
  #   remap:
  #     Super_L-Alt-Backspace:
  #       launch: ["chromium"]


